# Generated by Django 4.0.5 on 2022-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50, verbose_name='Home name1')),
                ('name2', models.CharField(max_length=50, verbose_name='Home name2')),
                ('about', models.TextField(verbose_name='Home about')),
                ('img1', models.ImageField(upload_to='media', verbose_name='Home img1')),
                ('img2', models.ImageField(upload_to='media', verbose_name='Home img2')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
            },
        ),
    ]
