# Generated by Django 4.0.5 on 2022-06-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='name2',
        ),
    ]
