# Generated by Django 4.0.5 on 2022-06-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_home_name2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='name1',
            new_name='name',
        ),
    ]
