# Generated by Django 4.0.5 on 2022-06-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name1_home_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='HomeProduct name')),
                ('price', models.IntegerField(verbose_name='HomeProduct price')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeProduct img')),
            ],
            options={
                'verbose_name': 'HomeProduct',
                'verbose_name_plural': 'HomeProducts',
            },
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Home name'),
        ),
    ]
