# Generated by Django 4.0.5 on 2022-06-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_homeproduct_name2_homeproduct_price2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProduct1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeProduct1 img')),
                ('name', models.CharField(max_length=50, verbose_name='HomeProduct1 name')),
                ('price', models.IntegerField(verbose_name='HomeProduct1 price')),
            ],
            options={
                'verbose_name': 'HomeProduct1',
                'verbose_name_plural': 'HomeProducts1',
            },
        ),
    ]
