# Generated by Django 4.0.5 on 2022-06-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_homeproduct1'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProduct2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeProduct2 img')),
                ('name', models.CharField(max_length=50, verbose_name='HomeProduct2 name')),
                ('price', models.IntegerField(verbose_name='HomeProduct2 price')),
            ],
            options={
                'verbose_name': 'HomeProduct2',
                'verbose_name_plural': 'HomeProducts2',
            },
        ),
    ]
