# Generated by Django 4.0.5 on 2022-06-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homeproduct2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eror404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Eror 404 img')),
                ('name1', models.CharField(max_length=50, verbose_name='Eror 404 name1')),
                ('about', models.TextField(verbose_name='Eror 404 about')),
                ('name2', models.CharField(max_length=50, verbose_name='Eror 404 name2')),
            ],
            options={
                'verbose_name': 'Eror 404',
                'verbose_name_plural': 'Erors 404',
            },
        ),
    ]
