# Generated by Django 4.0.5 on 2022-06-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_eror404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eror404',
            name='img',
        ),
        migrations.AddField(
            model_name='eror404',
            name='img1',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Eror 404 img1'),
        ),
        migrations.AddField(
            model_name='eror404',
            name='img2',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Eror 404 img2'),
        ),
    ]
