# Generated by Django 4.0.5 on 2022-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='ShopProduct img')),
                ('name', models.CharField(max_length=50, verbose_name='ShopProduct  name')),
                ('price', models.IntegerField(verbose_name='ShopProduct  price')),
            ],
            options={
                'verbose_name': 'ShopProduct',
                'verbose_name_plural': 'ShopProducts',
            },
        ),
    ]
