# Generated by Django 4.0.5 on 2022-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='img4',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Product_detail img4'),
        ),
    ]
