# Generated by Django 4.0.5 on 2022-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_detail_img4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='imgS1',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Product_detail imgS1'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='imgS2',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Product_detail imgS2'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='imgS3',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Product_detail imgS3'),
        ),
    ]
