# Generated by Django 4.0.5 on 2022-06-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='imgw',
            new_name='img2',
        ),
    ]
