# Generated by Django 4.0.5 on 2022-06-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_blog_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='name2',
        ),
    ]
