# Generated by Django 4.0.5 on 2022-06-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_blog_img2_remove_blog_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50, verbose_name='BlogSingle name1')),
                ('img1', models.ImageField(upload_to='media', verbose_name='BlogSingle img1')),
                ('about1', models.TextField(verbose_name='BlogSingle about1')),
                ('about2', models.TextField(verbose_name='BlogSingle about2')),
                ('about3', models.TextField(verbose_name='BlogSingle about3')),
                ('about4', models.TextField(verbose_name='BlogSingle about4')),
                ('img2', models.ImageField(upload_to='media', verbose_name='BlogSingle img2')),
                ('name2', models.CharField(max_length=50, verbose_name='BlogSingle name2')),
                ('about5', models.TextField(verbose_name='BlogSingle about5')),
            ],
            options={
                'verbose_name': 'BlogSingle',
                'verbose_name_plural': 'BlogSingles',
            },
        ),
    ]
