# Generated by Django 4.0.5 on 2022-06-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_blogsingle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsingle',
            name='about5',
        ),
        migrations.RemoveField(
            model_name='blogsingle',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='blogsingle',
            name='name2',
        ),
    ]
