# Generated by Django 4.0.5 on 2022-06-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_blogsingle_about5_remove_blogsingle_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSingle2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='BlogSingle2 name')),
                ('img', models.ImageField(upload_to='media', verbose_name='BlogSingle2 img')),
                ('about', models.TextField(verbose_name='BlogSingle2 about')),
            ],
            options={
                'verbose_name': 'BlogSingle2',
                'verbose_name_plural': 'BlogSingles2',
            },
        ),
    ]
