# Generated by Django 4.0.5 on 2022-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_blogsingle2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsingle2',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='BlogSingle2 name'),
        ),
    ]
