# Generated by Django 4.0.5 on 2022-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='img2',
            field=models.ImageField(null=True, upload_to='media', verbose_name='ShopProduct img2'),
        ),
    ]
