# Generated by Django 4.0.5 on 2022-06-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_shopproduct_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='img2',
        ),
    ]
