# Generated by Django 5.0.2 on 2024-03-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Detail Name'),
        ),
    ]
