# Generated by Django 5.0.2 on 2024-03-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_detail_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='Product_detail',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'detail', 'verbose_name_plural': 'details'},
        ),
    ]
